### ISSUE TITLE
Install Devise authentication

### ISSUE THREAD

**Issue by sarahpaz** [sarahpaz/pineappler#2]

**Comment by omenking** [comment]
Getting Started with Devise Authentication for Rails.
https://github.com/heartcombo/devise#starting-with-rails

**Comment by sarahpaz** [comment]
I've installed Devise and generated the User model [(feature/2-devise).](https://github.com/sarahpaz/pineappler/tree/feature/2-devise) I haven't migrated the db because the scheme is not yet defined. Can you review?

**Comment by omenking** [comment]
No need to ask me to review. You can proceed to migrate.

- [ ] Install the Devise frontend code so you can register and login.
